In [3]:
import pandas as pd
df=pd.read_csv("diseases.csv")
df

                                      name
0                         fungal infection
1                                  allergy
2                                     gerd
3                      chronic cholestasis
4                            drug reaction
5                      peptic ulcer diseae
6                                     aids
7                                 diabetes
8                          gastroenteritis
9                         bronchial asthma
10                            hypertension
11                                migraine
12                    cervical spondylosis
13            paralysis (brain hemorrhage)
14                                jaundice
15                                 malaria
16                             chicken pox
17                                  dengue
18                                 typhoid
19                             hepatitis a
20                             hepatitis b
21                             hepatitis c
22                             hepatitis d
23                             hepatitis e
24                     alcoholic hepatitis
25                            tuberculosis
26                             common cold
27                               pneumonia
28            dimorphic hemmorhoids(piles)
29                            heart attack
30                          varicose veins
31                          hypothyroidism
32                         hyperthyroidism
33                            hypoglycemia
34                         osteoarthristis
35                               arthritis
36  (vertigo) paroymsal positional vertigo
37                                    acne
38                 urinary tract infection
39                               psoriasis
40                                impetigo

In [10]:
disease_name=df["name"].dropna().unique().tolist()
print("Liste des maladies :", disease_name)

Liste des maladies : ['fungal infection', 'allergy', 'gerd', 'chronic cholestasis', 'drug reaction', 'peptic ulcer diseae', 'aids', 'diabetes', 'gastroenteritis', 'bronchial asthma', 'hypertension', 'migraine', 'cervical spondylosis', 'paralysis (brain hemorrhage)', 'jaundice', 'malaria', 'chicken pox', 'dengue', 'typhoid', 'hepatitis a', 'hepatitis b', 'hepatitis c', 'hepatitis d', 'hepatitis e', 'alcoholic hepatitis', 'tuberculosis', 'common cold', 'pneumonia', 'dimorphic hemmorhoids(piles)', 'heart attack', 'varicose veins', 'hypothyroidism', 'hyperthyroidism', 'hypoglycemia', 'osteoarthristis', 'arthritis', '(vertigo) paroymsal positional vertigo', 'acne', 'urinary tract infection', 'psoriasis', 'impetigo']

In [18]:
df1=pd.read_csv("precautions.csv")
df1

                                name
0                    stop irritation
1           consult nearest hospital
2                   stop taking drug
3                          follow up
4                    avoid oily food
..                               ...
91                   try acupuncture
92  stop eating solid food for while
93    try taking small sips of water
94             ease back into eating
95                       cover mouth

[96 rows x 1 columns]

In [20]:
preaucation_name=df1["name"].dropna().unique().tolist()
print(preaucation_name)

['stop irritation', 'consult nearest hospital', 'stop taking drug', 'follow up', 'avoid oily food', 'avoid non veg food', 'keep mosquitos out', 'apply calamine', 'cover area with bandage', 'use ice to compress itching', 'reduce stress', 'exercise', 'eat healthy', 'get proper sleep', 'wash hands with warm soapy water', 'stop bleeding using pressure', 'consult doctor', 'salt baths', 'avoid fatty spicy food', 'avoid lying down after eating', 'maintain healthy weight', 'cold baths', 'anti itch medicine', 'wash hands through', 'medication', 'acetaminophen', 'lie down', 'avoid sudden change in body', 'avoid abrupt head movment', 'relax', 'lie down on side', 'check in pulse', 'drink sugary drinks', 'bath twice', 'drink plenty of water', 'avoid too many products', 'have balanced diet', 'soak affected area in warm water', 'use antibiotics', 'remove scabs with wet compressed cloth', 'meditation', 'consume probiotic food', 'eliminate milk', 'limit alcohol', 'consume witch hazel', 'warm bath with epsom salt', 'consume alovera juice', 'drink vitamin c rich drinks', 'take vapour', 'avoid cold food', 'keep fever in check', 'use neem in bathing', 'consume neem leaves', 'take vaccine', 'avoid public places', 'use heating pad or cold pack', 'take otc pain reliver', 'massage', 'use lemon balm', 'take radioactive iodine treatment', 'increase vitamin c intake', 'drink cranberry juice', 'take probiotics', 'lie down flat and raise the leg high', 'use oinments', 'use vein compression', 'dont stand still for long', 'avoid open cuts', 'wear ppe if possible', 'eat high calorie vegitables', 'antiboitic therapy', 'vaccination', 'use detol or neem in bathing water', 'keep infected area dry', 'use clean cloths', 'use poloroid glasses in sun', 'switch to loose cloothing', 'take deep breaths', 'get away from trigger', 'seek help', 'stop alcohol consumption', 'consume milk thistle', 'eat fruits and high fiberous food', 'rest', 'drink papaya leaf juice', 'keep mosquitos away', 'keep hydrated', 'call ambulance', 'chew or swallow asprin', 'keep calm', 'use hot and cold therapy', 'try acupuncture', 'stop eating solid food for while', 'try taking small sips of water', 'ease back into eating', 'cover mouth']

In [22]:
df2=pd.read_csv("precautions.csv")
symptom_name=df2["name"].dropna().unique().tolist()
print(symptom_name)

['stop irritation', 'consult nearest hospital', 'stop taking drug', 'follow up', 'avoid oily food', 'avoid non veg food', 'keep mosquitos out', 'apply calamine', 'cover area with bandage', 'use ice to compress itching', 'reduce stress', 'exercise', 'eat healthy', 'get proper sleep', 'wash hands with warm soapy water', 'stop bleeding using pressure', 'consult doctor', 'salt baths', 'avoid fatty spicy food', 'avoid lying down after eating', 'maintain healthy weight', 'cold baths', 'anti itch medicine', 'wash hands through', 'medication', 'acetaminophen', 'lie down', 'avoid sudden change in body', 'avoid abrupt head movment', 'relax', 'lie down on side', 'check in pulse', 'drink sugary drinks', 'bath twice', 'drink plenty of water', 'avoid too many products', 'have balanced diet', 'soak affected area in warm water', 'use antibiotics', 'remove scabs with wet compressed cloth', 'meditation', 'consume probiotic food', 'eliminate milk', 'limit alcohol', 'consume witch hazel', 'warm bath with epsom salt', 'consume alovera juice', 'drink vitamin c rich drinks', 'take vapour', 'avoid cold food', 'keep fever in check', 'use neem in bathing', 'consume neem leaves', 'take vaccine', 'avoid public places', 'use heating pad or cold pack', 'take otc pain reliver', 'massage', 'use lemon balm', 'take radioactive iodine treatment', 'increase vitamin c intake', 'drink cranberry juice', 'take probiotics', 'lie down flat and raise the leg high', 'use oinments', 'use vein compression', 'dont stand still for long', 'avoid open cuts', 'wear ppe if possible', 'eat high calorie vegitables', 'antiboitic therapy', 'vaccination', 'use detol or neem in bathing water', 'keep infected area dry', 'use clean cloths', 'use poloroid glasses in sun', 'switch to loose cloothing', 'take deep breaths', 'get away from trigger', 'seek help', 'stop alcohol consumption', 'consume milk thistle', 'eat fruits and high fiberous food', 'rest', 'drink papaya leaf juice', 'keep mosquitos away', 'keep hydrated', 'call ambulance', 'chew or swallow asprin', 'keep calm', 'use hot and cold therapy', 'try acupuncture', 'stop eating solid food for while', 'try taking small sips of water', 'ease back into eating', 'cover mouth']